//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AdminLogin
    {
        public decimal user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
