//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bloggerregistration
    {
        public decimal Blogger_id { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Editby { get; set; }
        public string ProfilePict { get; set; }
        public string Password { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public string LoginUser { get; set; }
        public Nullable<decimal> Organization_id { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public string ProfilePictTest { get; set; }
    }
}
