//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CountryMaster
    {
        public decimal Country_id { get; set; }
        public string Country_Nm { get; set; }
    }
}
