//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SubCategory
    {
        public decimal Sub_cat_id { get; set; }
        public string Sub_cat_Nm { get; set; }
        public Nullable<decimal> Category_id { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public string EditeBy { get; set; }
    }
}
