<?xml version="1.0" encoding="utf-8"?><Database Name="db_rajputbook" Class="BlogPostDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=EPINHYDW1026\SQLEXPRESS;Initial Catalog=db_rajputbook;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_AdminLogin" Member="tb_AdminLogins">
    <Type Name="tb_AdminLogin">
      <Column Name="user_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_BlogCategory" Member="tb_BlogCategories">
    <Type Name="tb_BlogCategory">
      <Column Name="Category_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category_Nm" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_BloggerList" Member="tb_BloggerLists">
    <Type Name="tb_BloggerList">
      <Column Name="Blogger_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BloggerName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Organization_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Editby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProfilePict" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="StreetAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Zipcode" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProfPic" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tb_CountryMaster" Member="tb_CountryMasters">
    <Type Name="tb_CountryMaster">
      <Column Name="Country_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Country_Nm" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_PostList" Member="tb_PostLists">
    <Type Name="tb_PostList">
      <Column Name="Post_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Organization_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Category_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Blogger_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PostContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sub_cat_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_SubCategory" Member="tb_SubCategories">
    <Type Name="tb_SubCategory">
      <Column Name="Sub_cat_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sub_cat_Nm" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Category_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditeBy" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_UserRegistration" Member="tb_UserRegistrations">
    <Type Name="tb_UserRegistration">
      <Column Name="User_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrganizationNm" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_bloggerregistration" Member="tb_bloggerregistrations">
    <Type Name="tb_bloggerregistration">
      <Column Name="Blogger_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Editby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProfilePict" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="StreetAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Zipcode" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LoginUser" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Organization_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProfilePictTest" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EmailVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EmailCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobileVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MobileCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_OrganizationList" Member="tb_OrganizationLists">
    <Type Name="tb_OrganizationList">
      <Column Name="Organization_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Editby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProfilePict" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="StreetAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Zipcode" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LoginUser" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EmailCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MobileCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobileVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_Blogger" Method="sp_Blogger">
    <ElementType Name="sp_BloggerResult">
      <Column Name="Blogger_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_bloggerdiscription" Method="sp_bloggerdiscription">
    <Parameter Name="bloggerId" Type="System.Decimal" DbType="Decimal(18,0)" />
    <ElementType Name="sp_bloggerdiscriptionResult">
      <Column Name="Blogger_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ProfilePict" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="organizationname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_category" Method="sp_category">
    <ElementType Name="sp_categoryResult">
      <Column Name="Category_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Category_Nm" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Categoryview" Method="sp_Categoryview">
    <ElementType Name="sp_CategoryviewResult">
      <Column Name="subcategoryname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="categoryname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Category_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Sub_cat_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Countryfill" Method="sp_Countryfill">
    <ElementType Name="sp_CountryfillResult">
      <Column Name="Country_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Country_Nm" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Organization" Method="sp_Organization">
    <ElementType Name="sp_OrganizationResult">
      <Column Name="Organization_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_postlist" Method="sp_postlist">
    <Parameter Name="action" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Id" Parameter="id" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="blogCeteogryID" Type="System.Decimal" DbType="Decimal(18,0)" />
    <ElementType Name="sp_postlistResult">
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Organization_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="bloggerstatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="organizationstatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="organizationname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="bloggeremailid" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Blogger_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="bloggername" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Category_Nm" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Category_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Category_id1" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Sub_cat_Nm" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Sub_cat_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PostContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PostTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Post_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_subcategory" Method="sp_subcategory">
    <ElementType Name="sp_subcategoryResult">
      <Column Name="Sub_cat_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Sub_cat_Nm" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>