#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_rajputbook")]
public partial class BlogPostDataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttb_AdminLogin(tb_AdminLogin instance);
  partial void Updatetb_AdminLogin(tb_AdminLogin instance);
  partial void Deletetb_AdminLogin(tb_AdminLogin instance);
  partial void Inserttb_BlogCategory(tb_BlogCategory instance);
  partial void Updatetb_BlogCategory(tb_BlogCategory instance);
  partial void Deletetb_BlogCategory(tb_BlogCategory instance);
  partial void Inserttb_BloggerList(tb_BloggerList instance);
  partial void Updatetb_BloggerList(tb_BloggerList instance);
  partial void Deletetb_BloggerList(tb_BloggerList instance);
  partial void Inserttb_CountryMaster(tb_CountryMaster instance);
  partial void Updatetb_CountryMaster(tb_CountryMaster instance);
  partial void Deletetb_CountryMaster(tb_CountryMaster instance);
  partial void Inserttb_PostList(tb_PostList instance);
  partial void Updatetb_PostList(tb_PostList instance);
  partial void Deletetb_PostList(tb_PostList instance);
  partial void Inserttb_SubCategory(tb_SubCategory instance);
  partial void Updatetb_SubCategory(tb_SubCategory instance);
  partial void Deletetb_SubCategory(tb_SubCategory instance);
  partial void Inserttb_UserRegistration(tb_UserRegistration instance);
  partial void Updatetb_UserRegistration(tb_UserRegistration instance);
  partial void Deletetb_UserRegistration(tb_UserRegistration instance);
  partial void Inserttb_bloggerregistration(tb_bloggerregistration instance);
  partial void Updatetb_bloggerregistration(tb_bloggerregistration instance);
  partial void Deletetb_bloggerregistration(tb_bloggerregistration instance);
  partial void Inserttb_OrganizationList(tb_OrganizationList instance);
  partial void Updatetb_OrganizationList(tb_OrganizationList instance);
  partial void Deletetb_OrganizationList(tb_OrganizationList instance);
  #endregion
	
	public BlogPostDataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DataSourceConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BlogPostDataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BlogPostDataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BlogPostDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BlogPostDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tb_AdminLogin> tb_AdminLogins
	{
		get
		{
			return this.GetTable<tb_AdminLogin>();
		}
	}
	
	public System.Data.Linq.Table<tb_BlogCategory> tb_BlogCategories
	{
		get
		{
			return this.GetTable<tb_BlogCategory>();
		}
	}
	
	public System.Data.Linq.Table<tb_BloggerList> tb_BloggerLists
	{
		get
		{
			return this.GetTable<tb_BloggerList>();
		}
	}
	
	public System.Data.Linq.Table<tb_CountryMaster> tb_CountryMasters
	{
		get
		{
			return this.GetTable<tb_CountryMaster>();
		}
	}
	
	public System.Data.Linq.Table<tb_PostList> tb_PostLists
	{
		get
		{
			return this.GetTable<tb_PostList>();
		}
	}
	
	public System.Data.Linq.Table<tb_SubCategory> tb_SubCategories
	{
		get
		{
			return this.GetTable<tb_SubCategory>();
		}
	}
	
	public System.Data.Linq.Table<tb_UserRegistration> tb_UserRegistrations
	{
		get
		{
			return this.GetTable<tb_UserRegistration>();
		}
	}
	
	public System.Data.Linq.Table<tb_bloggerregistration> tb_bloggerregistrations
	{
		get
		{
			return this.GetTable<tb_bloggerregistration>();
		}
	}
	
	public System.Data.Linq.Table<tb_OrganizationList> tb_OrganizationLists
	{
		get
		{
			return this.GetTable<tb_OrganizationList>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Blogger")]
	public ISingleResult<sp_BloggerResult> sp_Blogger()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<sp_BloggerResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_bloggerdiscription")]
	public ISingleResult<sp_bloggerdiscriptionResult> sp_bloggerdiscription([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> bloggerId)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bloggerId);
		return ((ISingleResult<sp_bloggerdiscriptionResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_category")]
	public ISingleResult<sp_categoryResult> sp_category()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<sp_categoryResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Categoryview")]
	public ISingleResult<sp_CategoryviewResult> sp_Categoryview()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<sp_CategoryviewResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Countryfill")]
	public ISingleResult<sp_CountryfillResult> sp_Countryfill()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<sp_CountryfillResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Organization")]
	public ISingleResult<sp_OrganizationResult> sp_Organization()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<sp_OrganizationResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_postlist")]
	public ISingleResult<sp_postlistResult> sp_postlist([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Decimal(18,0)")] System.Nullable<decimal> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> blogCeteogryID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), action, id, blogCeteogryID);
		return ((ISingleResult<sp_postlistResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_subcategory")]
	public ISingleResult<sp_subcategoryResult> sp_subcategory()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<sp_subcategoryResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_AdminLogin")]
public partial class tb_AdminLogin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _user_id;
	
	private string _username;
	
	private string _password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(decimal value);
    partial void Onuser_idChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
	
	public tb_AdminLogin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_BlogCategory")]
public partial class tb_BlogCategory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Category_id;
	
	private string _Category_Nm;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategory_idChanging(decimal value);
    partial void OnCategory_idChanged();
    partial void OnCategory_NmChanging(string value);
    partial void OnCategory_NmChanged();
    #endregion
	
	public tb_BlogCategory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Category_id
	{
		get
		{
			return this._Category_id;
		}
		set
		{
			if ((this._Category_id != value))
			{
				this.OnCategory_idChanging(value);
				this.SendPropertyChanging();
				this._Category_id = value;
				this.SendPropertyChanged("Category_id");
				this.OnCategory_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_Nm", DbType="NVarChar(150)")]
	public string Category_Nm
	{
		get
		{
			return this._Category_Nm;
		}
		set
		{
			if ((this._Category_Nm != value))
			{
				this.OnCategory_NmChanging(value);
				this.SendPropertyChanging();
				this._Category_Nm = value;
				this.SendPropertyChanged("Category_Nm");
				this.OnCategory_NmChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_BloggerList")]
public partial class tb_BloggerList : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Blogger_id;
	
	private string _BloggerName;
	
	private string _email;
	
	private string _Phone;
	
	private System.Nullable<bool> _Active;
	
	private System.Nullable<decimal> _Organization_id;
	
	private string _Description;
	
	private System.Nullable<System.DateTime> _EntryDate;
	
	private string _Editby;
	
	private string _ProfilePict;
	
	private string _Address;
	
	private string _Password;
	
	private string _StreetAddress;
	
	private string _City;
	
	private string _State;
	
	private string _Zipcode;
	
	private string _Country;
	
	private string _Reason;
	
	private string _Status;
	
	private System.Data.Linq.Binary _ProfPic;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBlogger_idChanging(decimal value);
    partial void OnBlogger_idChanged();
    partial void OnBloggerNameChanging(string value);
    partial void OnBloggerNameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnOrganization_idChanging(System.Nullable<decimal> value);
    partial void OnOrganization_idChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnEntryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEntryDateChanged();
    partial void OnEditbyChanging(string value);
    partial void OnEditbyChanged();
    partial void OnProfilePictChanging(string value);
    partial void OnProfilePictChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnStreetAddressChanging(string value);
    partial void OnStreetAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipcodeChanging(string value);
    partial void OnZipcodeChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnProfPicChanging(System.Data.Linq.Binary value);
    partial void OnProfPicChanged();
    #endregion
	
	public tb_BloggerList()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blogger_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Blogger_id
	{
		get
		{
			return this._Blogger_id;
		}
		set
		{
			if ((this._Blogger_id != value))
			{
				this.OnBlogger_idChanging(value);
				this.SendPropertyChanging();
				this._Blogger_id = value;
				this.SendPropertyChanged("Blogger_id");
				this.OnBlogger_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloggerName", DbType="NVarChar(150)")]
	public string BloggerName
	{
		get
		{
			return this._BloggerName;
		}
		set
		{
			if ((this._BloggerName != value))
			{
				this.OnBloggerNameChanging(value);
				this.SendPropertyChanging();
				this._BloggerName = value;
				this.SendPropertyChanged("BloggerName");
				this.OnBloggerNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(150)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(150)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
	public System.Nullable<bool> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organization_id", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Organization_id
	{
		get
		{
			return this._Organization_id;
		}
		set
		{
			if ((this._Organization_id != value))
			{
				this.OnOrganization_idChanging(value);
				this.SendPropertyChanging();
				this._Organization_id = value;
				this.SendPropertyChanged("Organization_id");
				this.OnOrganization_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EntryDate
	{
		get
		{
			return this._EntryDate;
		}
		set
		{
			if ((this._EntryDate != value))
			{
				this.OnEntryDateChanging(value);
				this.SendPropertyChanging();
				this._EntryDate = value;
				this.SendPropertyChanged("EntryDate");
				this.OnEntryDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editby", DbType="NVarChar(50)")]
	public string Editby
	{
		get
		{
			return this._Editby;
		}
		set
		{
			if ((this._Editby != value))
			{
				this.OnEditbyChanging(value);
				this.SendPropertyChanging();
				this._Editby = value;
				this.SendPropertyChanged("Editby");
				this.OnEditbyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePict", DbType="NVarChar(MAX)")]
	public string ProfilePict
	{
		get
		{
			return this._ProfilePict;
		}
		set
		{
			if ((this._ProfilePict != value))
			{
				this.OnProfilePictChanging(value);
				this.SendPropertyChanging();
				this._ProfilePict = value;
				this.SendPropertyChanged("ProfilePict");
				this.OnProfilePictChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(150)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAddress", DbType="NVarChar(150)")]
	public string StreetAddress
	{
		get
		{
			return this._StreetAddress;
		}
		set
		{
			if ((this._StreetAddress != value))
			{
				this.OnStreetAddressChanging(value);
				this.SendPropertyChanging();
				this._StreetAddress = value;
				this.SendPropertyChanged("StreetAddress");
				this.OnStreetAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(150)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(150)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zipcode", DbType="NVarChar(150)")]
	public string Zipcode
	{
		get
		{
			return this._Zipcode;
		}
		set
		{
			if ((this._Zipcode != value))
			{
				this.OnZipcodeChanging(value);
				this.SendPropertyChanging();
				this._Zipcode = value;
				this.SendPropertyChanged("Zipcode");
				this.OnZipcodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(150)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this.OnCountryChanging(value);
				this.SendPropertyChanging();
				this._Country = value;
				this.SendPropertyChanged("Country");
				this.OnCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="NVarChar(MAX)")]
	public string Reason
	{
		get
		{
			return this._Reason;
		}
		set
		{
			if ((this._Reason != value))
			{
				this.OnReasonChanging(value);
				this.SendPropertyChanging();
				this._Reason = value;
				this.SendPropertyChanged("Reason");
				this.OnReasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfPic", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary ProfPic
	{
		get
		{
			return this._ProfPic;
		}
		set
		{
			if ((this._ProfPic != value))
			{
				this.OnProfPicChanging(value);
				this.SendPropertyChanging();
				this._ProfPic = value;
				this.SendPropertyChanged("ProfPic");
				this.OnProfPicChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_CountryMaster")]
public partial class tb_CountryMaster : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Country_id;
	
	private string _Country_Nm;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountry_idChanging(decimal value);
    partial void OnCountry_idChanged();
    partial void OnCountry_NmChanging(string value);
    partial void OnCountry_NmChanged();
    #endregion
	
	public tb_CountryMaster()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Country_id
	{
		get
		{
			return this._Country_id;
		}
		set
		{
			if ((this._Country_id != value))
			{
				this.OnCountry_idChanging(value);
				this.SendPropertyChanging();
				this._Country_id = value;
				this.SendPropertyChanged("Country_id");
				this.OnCountry_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_Nm", DbType="NVarChar(150)")]
	public string Country_Nm
	{
		get
		{
			return this._Country_Nm;
		}
		set
		{
			if ((this._Country_Nm != value))
			{
				this.OnCountry_NmChanging(value);
				this.SendPropertyChanging();
				this._Country_Nm = value;
				this.SendPropertyChanged("Country_Nm");
				this.OnCountry_NmChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_PostList")]
public partial class tb_PostList : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Post_id;
	
	private string _PostTitle;
	
	private System.Nullable<System.DateTime> _Date;
	
	private System.Nullable<bool> _Active;
	
	private System.Nullable<decimal> _Organization_id;
	
	private System.Nullable<decimal> _Category_id;
	
	private System.Nullable<decimal> _Blogger_id;
	
	private string _PostContent;
	
	private System.Nullable<System.DateTime> _EntryDate;
	
	private string _Status;
	
	private string _Reason;
	
	private System.Nullable<decimal> _Sub_cat_id;
	
	private string _Image;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPost_idChanging(decimal value);
    partial void OnPost_idChanged();
    partial void OnPostTitleChanging(string value);
    partial void OnPostTitleChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnOrganization_idChanging(System.Nullable<decimal> value);
    partial void OnOrganization_idChanged();
    partial void OnCategory_idChanging(System.Nullable<decimal> value);
    partial void OnCategory_idChanged();
    partial void OnBlogger_idChanging(System.Nullable<decimal> value);
    partial void OnBlogger_idChanged();
    partial void OnPostContentChanging(string value);
    partial void OnPostContentChanged();
    partial void OnEntryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEntryDateChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnSub_cat_idChanging(System.Nullable<decimal> value);
    partial void OnSub_cat_idChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    #endregion
	
	public tb_PostList()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Post_id
	{
		get
		{
			return this._Post_id;
		}
		set
		{
			if ((this._Post_id != value))
			{
				this.OnPost_idChanging(value);
				this.SendPropertyChanging();
				this._Post_id = value;
				this.SendPropertyChanged("Post_id");
				this.OnPost_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostTitle", DbType="NVarChar(50)")]
	public string PostTitle
	{
		get
		{
			return this._PostTitle;
		}
		set
		{
			if ((this._PostTitle != value))
			{
				this.OnPostTitleChanging(value);
				this.SendPropertyChanging();
				this._PostTitle = value;
				this.SendPropertyChanged("PostTitle");
				this.OnPostTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
	public System.Nullable<bool> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organization_id", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Organization_id
	{
		get
		{
			return this._Organization_id;
		}
		set
		{
			if ((this._Organization_id != value))
			{
				this.OnOrganization_idChanging(value);
				this.SendPropertyChanging();
				this._Organization_id = value;
				this.SendPropertyChanged("Organization_id");
				this.OnOrganization_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_id", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Category_id
	{
		get
		{
			return this._Category_id;
		}
		set
		{
			if ((this._Category_id != value))
			{
				this.OnCategory_idChanging(value);
				this.SendPropertyChanging();
				this._Category_id = value;
				this.SendPropertyChanged("Category_id");
				this.OnCategory_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blogger_id", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Blogger_id
	{
		get
		{
			return this._Blogger_id;
		}
		set
		{
			if ((this._Blogger_id != value))
			{
				this.OnBlogger_idChanging(value);
				this.SendPropertyChanging();
				this._Blogger_id = value;
				this.SendPropertyChanged("Blogger_id");
				this.OnBlogger_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostContent", DbType="NVarChar(MAX)")]
	public string PostContent
	{
		get
		{
			return this._PostContent;
		}
		set
		{
			if ((this._PostContent != value))
			{
				this.OnPostContentChanging(value);
				this.SendPropertyChanging();
				this._PostContent = value;
				this.SendPropertyChanged("PostContent");
				this.OnPostContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EntryDate
	{
		get
		{
			return this._EntryDate;
		}
		set
		{
			if ((this._EntryDate != value))
			{
				this.OnEntryDateChanging(value);
				this.SendPropertyChanging();
				this._EntryDate = value;
				this.SendPropertyChanged("EntryDate");
				this.OnEntryDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(MAX)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="NVarChar(MAX)")]
	public string Reason
	{
		get
		{
			return this._Reason;
		}
		set
		{
			if ((this._Reason != value))
			{
				this.OnReasonChanging(value);
				this.SendPropertyChanging();
				this._Reason = value;
				this.SendPropertyChanged("Reason");
				this.OnReasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_cat_id", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Sub_cat_id
	{
		get
		{
			return this._Sub_cat_id;
		}
		set
		{
			if ((this._Sub_cat_id != value))
			{
				this.OnSub_cat_idChanging(value);
				this.SendPropertyChanging();
				this._Sub_cat_id = value;
				this.SendPropertyChanged("Sub_cat_id");
				this.OnSub_cat_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NVarChar(MAX)")]
	public string Image
	{
		get
		{
			return this._Image;
		}
		set
		{
			if ((this._Image != value))
			{
				this.OnImageChanging(value);
				this.SendPropertyChanging();
				this._Image = value;
				this.SendPropertyChanged("Image");
				this.OnImageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_SubCategory")]
public partial class tb_SubCategory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Sub_cat_id;
	
	private string _Sub_cat_Nm;
	
	private System.Nullable<decimal> _Category_id;
	
	private System.Nullable<System.DateTime> _Entry_Date;
	
	private string _EditeBy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSub_cat_idChanging(decimal value);
    partial void OnSub_cat_idChanged();
    partial void OnSub_cat_NmChanging(string value);
    partial void OnSub_cat_NmChanged();
    partial void OnCategory_idChanging(System.Nullable<decimal> value);
    partial void OnCategory_idChanged();
    partial void OnEntry_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnEntry_DateChanged();
    partial void OnEditeByChanging(string value);
    partial void OnEditeByChanged();
    #endregion
	
	public tb_SubCategory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_cat_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Sub_cat_id
	{
		get
		{
			return this._Sub_cat_id;
		}
		set
		{
			if ((this._Sub_cat_id != value))
			{
				this.OnSub_cat_idChanging(value);
				this.SendPropertyChanging();
				this._Sub_cat_id = value;
				this.SendPropertyChanged("Sub_cat_id");
				this.OnSub_cat_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_cat_Nm", DbType="NVarChar(150)")]
	public string Sub_cat_Nm
	{
		get
		{
			return this._Sub_cat_Nm;
		}
		set
		{
			if ((this._Sub_cat_Nm != value))
			{
				this.OnSub_cat_NmChanging(value);
				this.SendPropertyChanging();
				this._Sub_cat_Nm = value;
				this.SendPropertyChanged("Sub_cat_Nm");
				this.OnSub_cat_NmChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_id", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Category_id
	{
		get
		{
			return this._Category_id;
		}
		set
		{
			if ((this._Category_id != value))
			{
				this.OnCategory_idChanging(value);
				this.SendPropertyChanging();
				this._Category_id = value;
				this.SendPropertyChanged("Category_id");
				this.OnCategory_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Entry_Date
	{
		get
		{
			return this._Entry_Date;
		}
		set
		{
			if ((this._Entry_Date != value))
			{
				this.OnEntry_DateChanging(value);
				this.SendPropertyChanging();
				this._Entry_Date = value;
				this.SendPropertyChanged("Entry_Date");
				this.OnEntry_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditeBy", DbType="NVarChar(150)")]
	public string EditeBy
	{
		get
		{
			return this._EditeBy;
		}
		set
		{
			if ((this._EditeBy != value))
			{
				this.OnEditeByChanging(value);
				this.SendPropertyChanging();
				this._EditeBy = value;
				this.SendPropertyChanged("EditeBy");
				this.OnEditeByChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_UserRegistration")]
public partial class tb_UserRegistration : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _User_id;
	
	private string _OrganizationNm;
	
	private string _ZipCode;
	
	private string _City;
	
	private string _State;
	
	private string _Country;
	
	private string _Email;
	
	private string _Password;
	
	private string _Address;
	
	private string _Phone;
	
	private System.Nullable<System.DateTime> _EntryDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_idChanging(decimal value);
    partial void OnUser_idChanged();
    partial void OnOrganizationNmChanging(string value);
    partial void OnOrganizationNmChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEntryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEntryDateChanged();
    #endregion
	
	public tb_UserRegistration()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal User_id
	{
		get
		{
			return this._User_id;
		}
		set
		{
			if ((this._User_id != value))
			{
				this.OnUser_idChanging(value);
				this.SendPropertyChanging();
				this._User_id = value;
				this.SendPropertyChanged("User_id");
				this.OnUser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationNm", DbType="NVarChar(150)")]
	public string OrganizationNm
	{
		get
		{
			return this._OrganizationNm;
		}
		set
		{
			if ((this._OrganizationNm != value))
			{
				this.OnOrganizationNmChanging(value);
				this.SendPropertyChanging();
				this._OrganizationNm = value;
				this.SendPropertyChanged("OrganizationNm");
				this.OnOrganizationNmChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(150)")]
	public string ZipCode
	{
		get
		{
			return this._ZipCode;
		}
		set
		{
			if ((this._ZipCode != value))
			{
				this.OnZipCodeChanging(value);
				this.SendPropertyChanging();
				this._ZipCode = value;
				this.SendPropertyChanged("ZipCode");
				this.OnZipCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(150)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(150)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(150)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this.OnCountryChanging(value);
				this.SendPropertyChanging();
				this._Country = value;
				this.SendPropertyChanged("Country");
				this.OnCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(150)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(150)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EntryDate
	{
		get
		{
			return this._EntryDate;
		}
		set
		{
			if ((this._EntryDate != value))
			{
				this.OnEntryDateChanging(value);
				this.SendPropertyChanging();
				this._EntryDate = value;
				this.SendPropertyChanged("EntryDate");
				this.OnEntryDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_bloggerregistration")]
public partial class tb_bloggerregistration : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Blogger_id;
	
	private string _Name;
	
	private string _email;
	
	private string _Phone;
	
	private System.Nullable<bool> _Active;
	
	private string _Description;
	
	private System.Nullable<System.DateTime> _EntryDate;
	
	private string _Editby;
	
	private string _ProfilePict;
	
	private string _Password;
	
	private string _StreetAddress;
	
	private string _City;
	
	private string _State;
	
	private string _Zipcode;
	
	private string _Country;
	
	private string _LoginUser;
	
	private System.Nullable<decimal> _Organization_id;
	
	private string _Status;
	
	private string _Reason;
	
	private string _ProfilePictTest;
	
	private System.Nullable<bool> _EmailVerified;
	
	private string _EmailCode;
	
	private System.Nullable<bool> _MobileVerified;
	
	private string _MobileCode;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBlogger_idChanging(decimal value);
    partial void OnBlogger_idChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnEntryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEntryDateChanged();
    partial void OnEditbyChanging(string value);
    partial void OnEditbyChanged();
    partial void OnProfilePictChanging(string value);
    partial void OnProfilePictChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnStreetAddressChanging(string value);
    partial void OnStreetAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipcodeChanging(string value);
    partial void OnZipcodeChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnLoginUserChanging(string value);
    partial void OnLoginUserChanged();
    partial void OnOrganization_idChanging(System.Nullable<decimal> value);
    partial void OnOrganization_idChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnProfilePictTestChanging(string value);
    partial void OnProfilePictTestChanged();
    partial void OnEmailVerifiedChanging(System.Nullable<bool> value);
    partial void OnEmailVerifiedChanged();
    partial void OnEmailCodeChanging(string value);
    partial void OnEmailCodeChanged();
    partial void OnMobileVerifiedChanging(System.Nullable<bool> value);
    partial void OnMobileVerifiedChanged();
    partial void OnMobileCodeChanging(string value);
    partial void OnMobileCodeChanged();
    #endregion
	
	public tb_bloggerregistration()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blogger_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Blogger_id
	{
		get
		{
			return this._Blogger_id;
		}
		set
		{
			if ((this._Blogger_id != value))
			{
				this.OnBlogger_idChanging(value);
				this.SendPropertyChanging();
				this._Blogger_id = value;
				this.SendPropertyChanged("Blogger_id");
				this.OnBlogger_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(150)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(150)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
	public System.Nullable<bool> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EntryDate
	{
		get
		{
			return this._EntryDate;
		}
		set
		{
			if ((this._EntryDate != value))
			{
				this.OnEntryDateChanging(value);
				this.SendPropertyChanging();
				this._EntryDate = value;
				this.SendPropertyChanged("EntryDate");
				this.OnEntryDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editby", DbType="NVarChar(50)")]
	public string Editby
	{
		get
		{
			return this._Editby;
		}
		set
		{
			if ((this._Editby != value))
			{
				this.OnEditbyChanging(value);
				this.SendPropertyChanging();
				this._Editby = value;
				this.SendPropertyChanged("Editby");
				this.OnEditbyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePict", DbType="NVarChar(MAX)")]
	public string ProfilePict
	{
		get
		{
			return this._ProfilePict;
		}
		set
		{
			if ((this._ProfilePict != value))
			{
				this.OnProfilePictChanging(value);
				this.SendPropertyChanging();
				this._ProfilePict = value;
				this.SendPropertyChanged("ProfilePict");
				this.OnProfilePictChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(150)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAddress", DbType="NVarChar(150)")]
	public string StreetAddress
	{
		get
		{
			return this._StreetAddress;
		}
		set
		{
			if ((this._StreetAddress != value))
			{
				this.OnStreetAddressChanging(value);
				this.SendPropertyChanging();
				this._StreetAddress = value;
				this.SendPropertyChanged("StreetAddress");
				this.OnStreetAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(150)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(150)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zipcode", DbType="NVarChar(150)")]
	public string Zipcode
	{
		get
		{
			return this._Zipcode;
		}
		set
		{
			if ((this._Zipcode != value))
			{
				this.OnZipcodeChanging(value);
				this.SendPropertyChanging();
				this._Zipcode = value;
				this.SendPropertyChanged("Zipcode");
				this.OnZipcodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(150)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this.OnCountryChanging(value);
				this.SendPropertyChanging();
				this._Country = value;
				this.SendPropertyChanged("Country");
				this.OnCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginUser", DbType="NVarChar(150)")]
	public string LoginUser
	{
		get
		{
			return this._LoginUser;
		}
		set
		{
			if ((this._LoginUser != value))
			{
				this.OnLoginUserChanging(value);
				this.SendPropertyChanging();
				this._LoginUser = value;
				this.SendPropertyChanged("LoginUser");
				this.OnLoginUserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organization_id", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Organization_id
	{
		get
		{
			return this._Organization_id;
		}
		set
		{
			if ((this._Organization_id != value))
			{
				this.OnOrganization_idChanging(value);
				this.SendPropertyChanging();
				this._Organization_id = value;
				this.SendPropertyChanged("Organization_id");
				this.OnOrganization_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="NVarChar(MAX)")]
	public string Reason
	{
		get
		{
			return this._Reason;
		}
		set
		{
			if ((this._Reason != value))
			{
				this.OnReasonChanging(value);
				this.SendPropertyChanging();
				this._Reason = value;
				this.SendPropertyChanged("Reason");
				this.OnReasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePictTest", DbType="NVarChar(MAX)")]
	public string ProfilePictTest
	{
		get
		{
			return this._ProfilePictTest;
		}
		set
		{
			if ((this._ProfilePictTest != value))
			{
				this.OnProfilePictTestChanging(value);
				this.SendPropertyChanging();
				this._ProfilePictTest = value;
				this.SendPropertyChanged("ProfilePictTest");
				this.OnProfilePictTestChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailVerified", DbType="Bit")]
	public System.Nullable<bool> EmailVerified
	{
		get
		{
			return this._EmailVerified;
		}
		set
		{
			if ((this._EmailVerified != value))
			{
				this.OnEmailVerifiedChanging(value);
				this.SendPropertyChanging();
				this._EmailVerified = value;
				this.SendPropertyChanged("EmailVerified");
				this.OnEmailVerifiedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailCode", DbType="NVarChar(50)")]
	public string EmailCode
	{
		get
		{
			return this._EmailCode;
		}
		set
		{
			if ((this._EmailCode != value))
			{
				this.OnEmailCodeChanging(value);
				this.SendPropertyChanging();
				this._EmailCode = value;
				this.SendPropertyChanged("EmailCode");
				this.OnEmailCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileVerified", DbType="Bit")]
	public System.Nullable<bool> MobileVerified
	{
		get
		{
			return this._MobileVerified;
		}
		set
		{
			if ((this._MobileVerified != value))
			{
				this.OnMobileVerifiedChanging(value);
				this.SendPropertyChanging();
				this._MobileVerified = value;
				this.SendPropertyChanged("MobileVerified");
				this.OnMobileVerifiedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileCode", DbType="NVarChar(50)")]
	public string MobileCode
	{
		get
		{
			return this._MobileCode;
		}
		set
		{
			if ((this._MobileCode != value))
			{
				this.OnMobileCodeChanging(value);
				this.SendPropertyChanging();
				this._MobileCode = value;
				this.SendPropertyChanged("MobileCode");
				this.OnMobileCodeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_OrganizationList")]
public partial class tb_OrganizationList : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Organization_id;
	
	private string _Name;
	
	private string _email;
	
	private string _Phone;
	
	private System.Nullable<bool> _Active;
	
	private string _Description;
	
	private System.Nullable<System.DateTime> _EntryDate;
	
	private string _Editby;
	
	private string _ProfilePict;
	
	private string _Password;
	
	private string _StreetAddress;
	
	private string _City;
	
	private string _State;
	
	private string _Zipcode;
	
	private string _Country;
	
	private string _LoginUser;
	
	private string _Status;
	
	private string _Reason;
	
	private string _EmailCode;
	
	private System.Nullable<bool> _EmailVerified;
	
	private string _MobileCode;
	
	private System.Nullable<bool> _MobileVerified;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrganization_idChanging(decimal value);
    partial void OnOrganization_idChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnEntryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEntryDateChanged();
    partial void OnEditbyChanging(string value);
    partial void OnEditbyChanged();
    partial void OnProfilePictChanging(string value);
    partial void OnProfilePictChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnStreetAddressChanging(string value);
    partial void OnStreetAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipcodeChanging(string value);
    partial void OnZipcodeChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnLoginUserChanging(string value);
    partial void OnLoginUserChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnEmailCodeChanging(string value);
    partial void OnEmailCodeChanged();
    partial void OnEmailVerifiedChanging(System.Nullable<bool> value);
    partial void OnEmailVerifiedChanged();
    partial void OnMobileCodeChanging(string value);
    partial void OnMobileCodeChanged();
    partial void OnMobileVerifiedChanging(System.Nullable<bool> value);
    partial void OnMobileVerifiedChanged();
    #endregion
	
	public tb_OrganizationList()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organization_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Organization_id
	{
		get
		{
			return this._Organization_id;
		}
		set
		{
			if ((this._Organization_id != value))
			{
				this.OnOrganization_idChanging(value);
				this.SendPropertyChanging();
				this._Organization_id = value;
				this.SendPropertyChanged("Organization_id");
				this.OnOrganization_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(150)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(150)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
	public System.Nullable<bool> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EntryDate
	{
		get
		{
			return this._EntryDate;
		}
		set
		{
			if ((this._EntryDate != value))
			{
				this.OnEntryDateChanging(value);
				this.SendPropertyChanging();
				this._EntryDate = value;
				this.SendPropertyChanged("EntryDate");
				this.OnEntryDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editby", DbType="NVarChar(50)")]
	public string Editby
	{
		get
		{
			return this._Editby;
		}
		set
		{
			if ((this._Editby != value))
			{
				this.OnEditbyChanging(value);
				this.SendPropertyChanging();
				this._Editby = value;
				this.SendPropertyChanged("Editby");
				this.OnEditbyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePict", DbType="NVarChar(MAX)")]
	public string ProfilePict
	{
		get
		{
			return this._ProfilePict;
		}
		set
		{
			if ((this._ProfilePict != value))
			{
				this.OnProfilePictChanging(value);
				this.SendPropertyChanging();
				this._ProfilePict = value;
				this.SendPropertyChanged("ProfilePict");
				this.OnProfilePictChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(150)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAddress", DbType="NVarChar(150)")]
	public string StreetAddress
	{
		get
		{
			return this._StreetAddress;
		}
		set
		{
			if ((this._StreetAddress != value))
			{
				this.OnStreetAddressChanging(value);
				this.SendPropertyChanging();
				this._StreetAddress = value;
				this.SendPropertyChanged("StreetAddress");
				this.OnStreetAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(150)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(150)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zipcode", DbType="NVarChar(150)")]
	public string Zipcode
	{
		get
		{
			return this._Zipcode;
		}
		set
		{
			if ((this._Zipcode != value))
			{
				this.OnZipcodeChanging(value);
				this.SendPropertyChanging();
				this._Zipcode = value;
				this.SendPropertyChanged("Zipcode");
				this.OnZipcodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(150)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this.OnCountryChanging(value);
				this.SendPropertyChanging();
				this._Country = value;
				this.SendPropertyChanged("Country");
				this.OnCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginUser", DbType="NVarChar(150)")]
	public string LoginUser
	{
		get
		{
			return this._LoginUser;
		}
		set
		{
			if ((this._LoginUser != value))
			{
				this.OnLoginUserChanging(value);
				this.SendPropertyChanging();
				this._LoginUser = value;
				this.SendPropertyChanged("LoginUser");
				this.OnLoginUserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="NVarChar(MAX)")]
	public string Reason
	{
		get
		{
			return this._Reason;
		}
		set
		{
			if ((this._Reason != value))
			{
				this.OnReasonChanging(value);
				this.SendPropertyChanging();
				this._Reason = value;
				this.SendPropertyChanged("Reason");
				this.OnReasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailCode", DbType="NVarChar(50)")]
	public string EmailCode
	{
		get
		{
			return this._EmailCode;
		}
		set
		{
			if ((this._EmailCode != value))
			{
				this.OnEmailCodeChanging(value);
				this.SendPropertyChanging();
				this._EmailCode = value;
				this.SendPropertyChanged("EmailCode");
				this.OnEmailCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailVerified", DbType="Bit")]
	public System.Nullable<bool> EmailVerified
	{
		get
		{
			return this._EmailVerified;
		}
		set
		{
			if ((this._EmailVerified != value))
			{
				this.OnEmailVerifiedChanging(value);
				this.SendPropertyChanging();
				this._EmailVerified = value;
				this.SendPropertyChanged("EmailVerified");
				this.OnEmailVerifiedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileCode", DbType="NVarChar(50)")]
	public string MobileCode
	{
		get
		{
			return this._MobileCode;
		}
		set
		{
			if ((this._MobileCode != value))
			{
				this.OnMobileCodeChanging(value);
				this.SendPropertyChanging();
				this._MobileCode = value;
				this.SendPropertyChanged("MobileCode");
				this.OnMobileCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileVerified", DbType="Bit")]
	public System.Nullable<bool> MobileVerified
	{
		get
		{
			return this._MobileVerified;
		}
		set
		{
			if ((this._MobileVerified != value))
			{
				this.OnMobileVerifiedChanging(value);
				this.SendPropertyChanging();
				this._MobileVerified = value;
				this.SendPropertyChanged("MobileVerified");
				this.OnMobileVerifiedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class sp_BloggerResult
{
	
	private decimal _Blogger_id;
	
	private string _Name;
	
	public sp_BloggerResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blogger_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Blogger_id
	{
		get
		{
			return this._Blogger_id;
		}
		set
		{
			if ((this._Blogger_id != value))
			{
				this._Blogger_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
}

public partial class sp_bloggerdiscriptionResult
{
	
	private decimal _Blogger_id;
	
	private string _Description;
	
	private System.Nullable<System.DateTime> _EntryDate;
	
	private string _Name;
	
	private string _ProfilePict;
	
	private string _organizationname;
	
	public sp_bloggerdiscriptionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blogger_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Blogger_id
	{
		get
		{
			return this._Blogger_id;
		}
		set
		{
			if ((this._Blogger_id != value))
			{
				this._Blogger_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EntryDate
	{
		get
		{
			return this._EntryDate;
		}
		set
		{
			if ((this._EntryDate != value))
			{
				this._EntryDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePict", DbType="NVarChar(MAX)")]
	public string ProfilePict
	{
		get
		{
			return this._ProfilePict;
		}
		set
		{
			if ((this._ProfilePict != value))
			{
				this._ProfilePict = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizationname", DbType="NVarChar(150)")]
	public string organizationname
	{
		get
		{
			return this._organizationname;
		}
		set
		{
			if ((this._organizationname != value))
			{
				this._organizationname = value;
			}
		}
	}
}

public partial class sp_categoryResult
{
	
	private decimal _Category_id;
	
	private string _Category_Nm;
	
	public sp_categoryResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Category_id
	{
		get
		{
			return this._Category_id;
		}
		set
		{
			if ((this._Category_id != value))
			{
				this._Category_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_Nm", DbType="NVarChar(150)")]
	public string Category_Nm
	{
		get
		{
			return this._Category_Nm;
		}
		set
		{
			if ((this._Category_Nm != value))
			{
				this._Category_Nm = value;
			}
		}
	}
}

public partial class sp_CategoryviewResult
{
	
	private string _subcategoryname;
	
	private string _categoryname;
	
	private System.Nullable<decimal> _Category_id;
	
	private decimal _Sub_cat_id;
	
	public sp_CategoryviewResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subcategoryname", DbType="NVarChar(150)")]
	public string subcategoryname
	{
		get
		{
			return this._subcategoryname;
		}
		set
		{
			if ((this._subcategoryname != value))
			{
				this._subcategoryname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryname", DbType="NVarChar(150)")]
	public string categoryname
	{
		get
		{
			return this._categoryname;
		}
		set
		{
			if ((this._categoryname != value))
			{
				this._categoryname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_id", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Category_id
	{
		get
		{
			return this._Category_id;
		}
		set
		{
			if ((this._Category_id != value))
			{
				this._Category_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_cat_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Sub_cat_id
	{
		get
		{
			return this._Sub_cat_id;
		}
		set
		{
			if ((this._Sub_cat_id != value))
			{
				this._Sub_cat_id = value;
			}
		}
	}
}

public partial class sp_CountryfillResult
{
	
	private decimal _Country_id;
	
	private string _Country_Nm;
	
	public sp_CountryfillResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Country_id
	{
		get
		{
			return this._Country_id;
		}
		set
		{
			if ((this._Country_id != value))
			{
				this._Country_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_Nm", DbType="NVarChar(150)")]
	public string Country_Nm
	{
		get
		{
			return this._Country_Nm;
		}
		set
		{
			if ((this._Country_Nm != value))
			{
				this._Country_Nm = value;
			}
		}
	}
}

public partial class sp_OrganizationResult
{
	
	private decimal _Organization_id;
	
	private string _Name;
	
	public sp_OrganizationResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organization_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Organization_id
	{
		get
		{
			return this._Organization_id;
		}
		set
		{
			if ((this._Organization_id != value))
			{
				this._Organization_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
}

public partial class sp_postlistResult
{
	
	private System.Nullable<System.DateTime> _Date;
	
	private decimal _Organization_id;
	
	private string _bloggerstatus;
	
	private string _organizationstatus;
	
	private string _Reason;
	
	private System.Nullable<bool> _Active;
	
	private string _organizationname;
	
	private string _bloggeremailid;
	
	private decimal _Blogger_id;
	
	private string _bloggername;
	
	private string _Category_Nm;
	
	private decimal _Category_id;
	
	private System.Nullable<decimal> _Category_id1;
	
	private string _Sub_cat_Nm;
	
	private decimal _Sub_cat_id;
	
	private string _Image;
	
	private System.Nullable<System.DateTime> _EntryDate;
	
	private string _PostContent;
	
	private string _PostTitle;
	
	private decimal _Post_id;
	
	private string _Status;
	
	public sp_postlistResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this._Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organization_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Organization_id
	{
		get
		{
			return this._Organization_id;
		}
		set
		{
			if ((this._Organization_id != value))
			{
				this._Organization_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bloggerstatus", DbType="NVarChar(50)")]
	public string bloggerstatus
	{
		get
		{
			return this._bloggerstatus;
		}
		set
		{
			if ((this._bloggerstatus != value))
			{
				this._bloggerstatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizationstatus", DbType="NVarChar(50)")]
	public string organizationstatus
	{
		get
		{
			return this._organizationstatus;
		}
		set
		{
			if ((this._organizationstatus != value))
			{
				this._organizationstatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="NVarChar(MAX)")]
	public string Reason
	{
		get
		{
			return this._Reason;
		}
		set
		{
			if ((this._Reason != value))
			{
				this._Reason = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
	public System.Nullable<bool> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this._Active = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizationname", DbType="NVarChar(150)")]
	public string organizationname
	{
		get
		{
			return this._organizationname;
		}
		set
		{
			if ((this._organizationname != value))
			{
				this._organizationname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bloggeremailid", DbType="NVarChar(150)")]
	public string bloggeremailid
	{
		get
		{
			return this._bloggeremailid;
		}
		set
		{
			if ((this._bloggeremailid != value))
			{
				this._bloggeremailid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blogger_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Blogger_id
	{
		get
		{
			return this._Blogger_id;
		}
		set
		{
			if ((this._Blogger_id != value))
			{
				this._Blogger_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bloggername", DbType="NVarChar(150)")]
	public string bloggername
	{
		get
		{
			return this._bloggername;
		}
		set
		{
			if ((this._bloggername != value))
			{
				this._bloggername = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_Nm", DbType="NVarChar(150)")]
	public string Category_Nm
	{
		get
		{
			return this._Category_Nm;
		}
		set
		{
			if ((this._Category_Nm != value))
			{
				this._Category_Nm = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Category_id
	{
		get
		{
			return this._Category_id;
		}
		set
		{
			if ((this._Category_id != value))
			{
				this._Category_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_id1", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Category_id1
	{
		get
		{
			return this._Category_id1;
		}
		set
		{
			if ((this._Category_id1 != value))
			{
				this._Category_id1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_cat_Nm", DbType="NVarChar(150)")]
	public string Sub_cat_Nm
	{
		get
		{
			return this._Sub_cat_Nm;
		}
		set
		{
			if ((this._Sub_cat_Nm != value))
			{
				this._Sub_cat_Nm = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_cat_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Sub_cat_id
	{
		get
		{
			return this._Sub_cat_id;
		}
		set
		{
			if ((this._Sub_cat_id != value))
			{
				this._Sub_cat_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NVarChar(MAX)")]
	public string Image
	{
		get
		{
			return this._Image;
		}
		set
		{
			if ((this._Image != value))
			{
				this._Image = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EntryDate
	{
		get
		{
			return this._EntryDate;
		}
		set
		{
			if ((this._EntryDate != value))
			{
				this._EntryDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostContent", DbType="NVarChar(MAX)")]
	public string PostContent
	{
		get
		{
			return this._PostContent;
		}
		set
		{
			if ((this._PostContent != value))
			{
				this._PostContent = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostTitle", DbType="NVarChar(50)")]
	public string PostTitle
	{
		get
		{
			return this._PostTitle;
		}
		set
		{
			if ((this._PostTitle != value))
			{
				this._PostTitle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Post_id
	{
		get
		{
			return this._Post_id;
		}
		set
		{
			if ((this._Post_id != value))
			{
				this._Post_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(MAX)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this._Status = value;
			}
		}
	}
}

public partial class sp_subcategoryResult
{
	
	private decimal _Sub_cat_id;
	
	private string _Sub_cat_Nm;
	
	public sp_subcategoryResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_cat_id", DbType="Decimal(18,0) NOT NULL")]
	public decimal Sub_cat_id
	{
		get
		{
			return this._Sub_cat_id;
		}
		set
		{
			if ((this._Sub_cat_id != value))
			{
				this._Sub_cat_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_cat_Nm", DbType="NVarChar(150)")]
	public string Sub_cat_Nm
	{
		get
		{
			return this._Sub_cat_Nm;
		}
		set
		{
			if ((this._Sub_cat_Nm != value))
			{
				this._Sub_cat_Nm = value;
			}
		}
	}
}
#pragma warning restore 1591
